# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('dob', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
