# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='msgtext',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
