# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0003_remove_patientmodel_msgtext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmodel',
            options={'ordering': ['dob']},
        ),
    ]
