# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0004_auto_20161122_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='mailsent',
            field=models.BooleanField(default=False),
        ),
    ]
